name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test_java:
    name: Test Maven Project
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      id-token: write
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  test_javascript:
    name: Test JavaScript Project
    strategy:
      matrix:
        node: [ lts/* ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
      id-token: write

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: vite-demo

      - name: Run tests
        run: pnpm test
        working-directory: vite-demo
